Replace tdex with dex vulpem
vulpemventures/vulpemcom pull request #39
Opened 2022-02-02 12:31 UTC by bordalix

Fixes #38 

This PR changes `TDex Cli` with `TDEX`:
- On homepage, with screenshot of dex.vulpem.com
- On footer and menus
- On CSS, class `tdex-cli` with `tdex`
- Adds new image `dex.mockup.png`

@tiero please review

2022-02-02 12:59 UTC, tiero commented on src/401.html
> +                <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 13:00 UTC, tiero commented on src/404.html
> +                  <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                  <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 13:00 UTC, tiero commented on src/about.html
> +                <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 13:00 UTC, tiero commented on src/carrers.html
> +                <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 13:00 UTC, tiero commented on src/index.html
> +                <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 13:01 UTC, tiero commented on src/marina.html
> +                <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 13:01 UTC, tiero commented on src/nigiri.html
> +                <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 13:01 UTC, tiero commented on src/solutions.html
> +                <div class="dropdown-nav-item-title"><strong class="text-regular">Dex Vulpem</strong></div>
```suggestion
                <div class="dropdown-nav-item-title"><strong class="text-regular">TDEX</strong></div>
```

2022-02-02 21:43 UTC, tiero requested changes
all TDEX links should have target="_blank"

2022-02-03 11:08 UTC, bordalix commented
> all TDEX links should have target="_blank"

Fixed in 27b3c24

2022-02-03 12:27 UTC, merged